import eslint from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    // `dist/**` is build output. The entry shims (index.js, app.js, server.js,
    // src/index.js and the literal `*.js` file) are generated by
    // scripts/ensure-pterodactyl.mjs and are not hand-written source, so they
    // are excluded instead of being linted as Node scripts.
    ignores: [
      "dist/**",
      "node_modules/**",
      "index.js",
      "app.js",
      "server.js",
      "src/index.js",
      "*.js",
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["src/**/*.ts"],
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
);
